---
version: 3

##### build_arg_defaults:
#####   ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.1
  ansible_runner:
    package_pip: ansible-runner
  python_interpreter:
      package_system: "python3.9"
      python_path: "/usr/bin/python3.9"
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest

additional_build_files:
    - src: ansible.cfg
      dest: configs

additional_build_steps:
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg ~/.ansible.cfg
    - RUN pip3 install --upgrade pip setuptools

  prepend_builder:
    - RUN pip3 install --upgrade pip setuptools

  prepend_final:
    - RUN pip3 install --upgrade pip setuptools
    - RUN whoami
    - RUN cat /etc/os-release

  append_final:
    - RUN echo This is a post-install command!
    - RUN alternatives --set python /usr/bin/python3.9
    - RUN alternatives --set python3 /usr/bin/python3.9
    - RUN pip3 install --upgrade pip setuptools
    - RUN pip3 install pyopenssl --upgrade
